### ISSUE TITLE
Need a table or list to show calculate results in which pieces of boards are grouped by cabinet which they belong to.

### ISSUE THREAD

**Issue by guanzhou-zhao** [guanzhou-zhao/calculate-cabinet-plan#2]
- [x] show dimensions of the cabinet
- [ ] pieces of boards that form the cabinet are listed in order with description, qty, dimensions, edge info color
- [x] a sample picture of the cabinet

**Comment by wendy-chi** [comment]
the title of this issue is not clear. it should be declared the result is ordered by what element of cabinet.

**Comment by wendy-chi** [comment]
> _pieces of boards that form the cabinet are listed in order with description, qty, dimensions, edge info color_

Question: 
what kind of order?

**Comment by guanzhou-zhao** [comment]
@wendy-chi as your request, I changed the title of the issue
